// Single source of truth for API paths. Backend must implement these.
// See CONTRACT.md for request/response shapes.
export const EP = {
  login: "/auth/login",
  me: "/auth/me",
  facilities: "/facilities",
  chambers: "/chambers",
  devices: "/devices",
  gateways: "/gateways",
  gatewayById: (id) => `/gateways/${id}`,
  alerts: "/alerts",
  alertAck: (id) => `/alerts/${id}/ack`,
  alertResolve: (id) => `/alerts/${id}/resolve`,
  alertRules: "/alert-rules",
  passwordReset: "/auth/password-reset",
  notifications: "/notifications",
  notificationsReadAll: "/notifications/read-all",
  notificationRead: (id) => `/notifications/${id}/read`,
  workOrders: "/work-orders",
  dispatch: "/dispatch",
  inventory: "/inventory",  reports: "/reports",
  reportsMetrics: "/reports/metrics",
  reportGenerate: (id) => `/reports/${id}/generate`,
  reportsSchedule: "/reports/schedule",
  audit: "/audit",
  users: "/admin/users",
  usersInvite: "/users/invite",
  roles: "/roles",
  telemetryHistory: "/telemetry/history",
};
