"""Pydantic schemas for Device and Alerts."""
from __future__ import annotations

import uuid
from datetime import datetime

from pydantic import BaseModel


# ─── Device ───────────────────────────────────────────────────────────────────

class DeviceBase(BaseModel):
    name: str
    location_lat: float | None = None
    location_lng: float | None = None
    location_label: str | None = None


class DeviceCreate(DeviceBase):
    # thing_name auto-generated by backend
    pass


class DeviceUpdate(DeviceBase):
    is_active: bool | None = None


class DeviceResponse(DeviceBase):
    id: uuid.UUID
    organization_id: uuid.UUID
    status: str
    firmware_version: str | None
    last_seen: datetime | None
    thing_name: str | None
    is_active: bool
    created_at: datetime

    model_config = {"from_attributes": True}


# ─── Alert ────────────────────────────────────────────────────────────────────

class AlertResponse(BaseModel):
    id: uuid.UUID
    device_id: uuid.UUID
    organization_id: uuid.UUID
    type: str
    severity: str
    message: str
    is_resolved: bool
    resolved_at: datetime | None
    created_at: datetime

    model_config = {"from_attributes": True}


class AlertResolveRequest(BaseModel):
    resolved: bool = True
